import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#1976d2',
    primaryContainer: '#e3f2fd',
    secondary: '#03dac6',
    secondaryContainer: '#a7f3d0',
    tertiary: '#6750a4',
    tertiaryContainer: '#e8def8',
    surface: '#fefbff',
    surfaceVariant: '#e7e0ec',
    surfaceContainerHighest: '#e6e0e9',
    background: '#fefbff',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#001d32',
    onSecondary: '#00382a',
    onSecondaryContainer: '#002106',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#21005d',
    onSurface: '#1c1b1f',
    onSurfaceVariant: '#49454f',
    onError: '#ffffff',
    onErrorContainer: '#410002',
    onBackground: '#1c1b1f',
    outline: '#79747e',
    outlineVariant: '#cac4d0',
    inverseSurface: '#313033',
    inverseOnSurface: '#f4eff4',
    inversePrimary: '#90caf9',
    shadow: '#000000',
    scrim: '#000000',
  },
};

